### ISSUE TITLE
Russian Icons/Letters and other special characters not being supported by the font used in the software

### ISSUE THREAD

**Issue by SanityCS** [hawolt/JamAlong#3]
![image](https://github.com/hawolt/JamAlong/assets/144701198/6e72aa42-aaa8-44cd-b8f0-aa98401a049a)

**Comment by hawolt** [comment]
taking font recommendations

**Comment by hawolt** [comment]
![image](https://github.com/hawolt/JamAlong/assets/45050975/c9929563-9bab-47c0-b137-74e237046c5e)
seems to be working for me currently, closing this until someone else experiences the same issue
